---
apiVersion: v1
kind: Namespace
metadata:
  name: whizdome

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: whizdome
  labels:
    app: portfolio-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolio-app
        image: whizdome/portfolio-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-svc
  namespace: whizdome
  labels:
    app: portfolio-app
spec:
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer